### PR TITLE
Shikham12 patch 2

### PR DESCRIPTION
**Pull request by shikham12**
#10 All the headlines are now having a consistent format.

### CODE REVIEW

**Comment by SurajSanap** [comment]
Dear @shikham12,

I extend my gratitude for your contributions to our app, College.ai
I kindly request that you provide a detailed description of your work and include relevant screenshots in your pull request. This will facilitate the review process for our team.
Thank you for your cooperation.

**Comment by SurajSanap** [comment]
also tag to `issue` you are working on

**Comment by shikham12** [comment]
can you please guide me on to how to tag to issue

**Comment by shikham12** [comment]
Can you please guide me how to tag to issue?

**Comment by SurajSanap** [comment]
image

tag issue means  - just write issue number in your PR description ( e.g #18 )

**Pull request closed without merging**
