### PR TITLE
Update code formatting to comply with black & isort standards

### PR DESCRIPTION
**Pull request by Devasy23**
### Description

This PR updates the codebase to comply with `black` formatting standards and `isort` ordering of imports. These changes ensure that the code is consistently formatted and well-organized, enhancing readability and maintainability. No functional changes have been made to the code.

Fixes # (issue)

### Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### Additional Notes

These formatting changes are part of my contribution to the **GirlScript Summer of Code (GSSoC)**. Kindly assign this PR a **level 2** and grant me the corresponding points. Thank you!

### CODE REVIEW

**Comment by DiptiSanap** [comment]
Fix the Conflicts.

**Comment by Devasy23** [comment]
@DiptiSanap fixed the conflicts!!

**Comment by Devasy23** [comment]
updated the branch

**Review by Devasy23 — COMMENTED** [review]
updated the branch

**Comment by Devasy23** [comment]
I have completed my tasks for this pull request and it is ready for review and merging. Could you please assign the 'gssoc' tag and the appropriate level to it? I propose that it be classified as 'level 2'. Thank you.

**Pull request closed without merging**
