### PR TITLE
Update User.py

### PR DESCRIPTION
**Pull request by asrithaMulugoju**
### Description

Error: The original code did not properly handle password hashing and verification, causing security vulnerabilities. There were also issues with the Google OAuth2 authentication flow and minor typos.

Modification:

- Implemented password hashing with generate_password_hash during signup.
- Verified passwords with check_password_hash during login.
- Corrected the use of experimental_get_query_params in Streamlit.
- Fixed a typo in the show_login_button function.

Fixes Issue #105  

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by SurajSanap** [comment]
there are some issues during `Sign up
`
image

**Comment by asrithaMulugoju** [comment]
Okay, I will try to resolve it and will send you the updated code. Thank you!

**Comment by SurajSanap** [comment]
Hey @asrithaMulugoju , could I have your LinkedIn profile? I’d like to give a shoutout to the College.ai project contributors on LinkedIn.

**Comment by SurajSanap** [comment]
Hey @lassmara, could I have your LinkedIn profile? I’d like to give a shoutout to the College.ai project contributors on LinkedIn.

**Pull request merged**
