### PR TITLE
Add the contest calendar module

### LINKED ISSUE #94: [Feature]: Want to Add "Coding Contest" Section.
Want to add a coding contest section where the student can get all the information about the upcoming coding contest from various platform like Leetcode, Codechef, GFG , HackerRank. CodeForces etc 
Please assign me this issue under gssoc24

### PR DESCRIPTION
**Pull request by Shraman-jain**
### Description
I have added a coding contest calendar module where student can get all the details of upcoming contest

Fixes #94 

### Type of change

Please delete options that are not relevant.
- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update
 
### Checklist:
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings

### Screenshots (if appropriate)
Coding_Calendar

### Additional Notes

Can you please tag this issue of level 3 as i have created a new module from scratch!

### CODE REVIEW

**Comment by SurajSanap** [comment]
There is an error:

image

**Comment by Shraman-jain** [comment]
Is that error resolved ? or should i resolve and raise anther PR?

**Comment by Shraman-jain** [comment]
Okay sir thanks

**Comment by Shraman-jain** [comment]
@SurajSanap Sir is the error is still comming because it is still showing Revert contest calendar bug? I have updated the requirements.txt as well ??sorry for any mistake but I have updated readme and requirement.txt in the new PR

**Pull request merged**
