### PR TITLE
Changed_Account_section_and_added_job_tracker

### LINKED ISSUE #118: Re-Build USER.py Page
There are many issues on the user page. Rebuild it with optimized code.

image

### PR DESCRIPTION
**Pull request by Shraman-jain**
### Description

Added a job management tool and also added login signup functionality with proper sqlite database with this PR i have solved three major issues 

Fixes #118 #138 #114 

### Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### Additional Notes

Please provide any additional notes regarding this pull request.

### CODE REVIEW

**Comment by Shraman-jain** [comment]
@SurajSanap please review my PR

**Review by SurajSanap — APPROVED** [review]
Updated requirements.txt
Working fine.

**Comment by SurajSanap** [comment]
Hey @Shraman-jain, That was an **amazing** contribution. I appreciate your efforts. 
Thanks.

**Comment by Shraman-jain** [comment]
you have added level 1 tag?? i have solved three big issues please at least update the level tag and also give me score accordingly please

**Comment by SurajSanap** [comment]
already added.

**Comment by Shraman-jain** [comment]
@SurajSanap you have added level -1 tag here

**Comment by SurajSanap** [comment]
Is it okay? Could you please provide more details about level -1? I am unable to understand.

**Comment by Shraman-jain** [comment]
@SurajSanap can you share your discord id i can tell you there

**Pull request merged**
